apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index
  namespace: default
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head><title>Welcome to My Nginx</title></head>
    <body><h1>Hello from PRAKASH ddd!</h1></body>
    </html>

